/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssemblyRouteImport } from './routes/assembly'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CleaningRouteImport } from './routes/cleaning'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UsedRouteImport } from './routes/used'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as PrebuiltsIndexRouteImport } from './routes/prebuilts.index'
import { Route as PrebuiltsIdRouteImport } from './routes/prebuilts.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyRoute = AssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningRoute = CleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UsedRoute = UsedRouteImport.update({
  id: '/used',
  path: '/used',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrebuiltsIndexRoute = PrebuiltsIndexRouteImport.update({
  id: '/prebuilts/',
  path: '/prebuilts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrebuiltsIdRoute = PrebuiltsIdRouteImport.update({
  id: '/prebuilts/$id',
  path: '/prebuilts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assembly': typeof AssemblyRoute
  '/builder': typeof BuilderRoute
  '/cleaning': typeof CleaningRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/inspection': typeof InspectionRoute
  '/search': typeof SearchRoute
  '/used': typeof UsedRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/prebuilts/$id': typeof PrebuiltsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/guides/': typeof GuidesIndexRoute
  '/prebuilts/': typeof PrebuiltsIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assembly': typeof AssemblyRoute
  '/builder': typeof BuilderRoute
  '/cleaning': typeof CleaningRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/inspection': typeof InspectionRoute
  '/search': typeof SearchRoute
  '/used': typeof UsedRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/prebuilts/$id': typeof PrebuiltsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/guides': typeof GuidesIndexRoute
  '/prebuilts': typeof PrebuiltsIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assembly': typeof AssemblyRoute
  '/builder': typeof BuilderRoute
  '/cleaning': typeof CleaningRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/inspection': typeof InspectionRoute
  '/search': typeof SearchRoute
  '/used': typeof UsedRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/prebuilts/$id': typeof PrebuiltsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/guides/': typeof GuidesIndexRoute
  '/prebuilts/': typeof PrebuiltsIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assembly'
    | '/builder'
    | '/cleaning'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/inspection'
    | '/search'
    | '/used'
    | '/guides/$slug'
    | '/prebuilts/$id'
    | '/products/$id'
    | '/reports/$id'
    | '/guides/'
    | '/prebuilts/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assembly'
    | '/builder'
    | '/cleaning'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/inspection'
    | '/search'
    | '/used'
    | '/guides/$slug'
    | '/prebuilts/$id'
    | '/products/$id'
    | '/reports/$id'
    | '/guides'
    | '/prebuilts'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assembly'
    | '/builder'
    | '/cleaning'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/inspection'
    | '/search'
    | '/used'
    | '/guides/$slug'
    | '/prebuilts/$id'
    | '/products/$id'
    | '/reports/$id'
    | '/guides/'
    | '/prebuilts/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssemblyRoute: typeof AssemblyRoute
  BuilderRoute: typeof BuilderRoute
  CleaningRoute: typeof CleaningRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  InspectionRoute: typeof InspectionRoute
  SearchRoute: typeof SearchRoute
  UsedRoute: typeof UsedRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PrebuiltsIdRoute: typeof PrebuiltsIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ReportsIdRoute: typeof ReportsIdRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PrebuiltsIndexRoute: typeof PrebuiltsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly': {
      id: '/assembly'
      path: '/assembly'
      fullPath: '/assembly'
      preLoaderRoute: typeof AssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning': {
      id: '/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof CleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/used': {
      id: '/used'
      path: '/used'
      fullPath: '/used'
      preLoaderRoute: typeof UsedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prebuilts/': {
      id: '/prebuilts/'
      path: '/prebuilts'
      fullPath: '/prebuilts/'
      preLoaderRoute: typeof PrebuiltsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prebuilts/$id': {
      id: '/prebuilts/$id'
      path: '/prebuilts/$id'
      fullPath: '/prebuilts/$id'
      preLoaderRoute: typeof PrebuiltsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssemblyRoute: AssemblyRoute,
  BuilderRoute: BuilderRoute,
  CleaningRoute: CleaningRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  InspectionRoute: InspectionRoute,
  SearchRoute: SearchRoute,
  UsedRoute: UsedRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PrebuiltsIdRoute: PrebuiltsIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ReportsIdRoute: ReportsIdRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PrebuiltsIndexRoute: PrebuiltsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
